version: '3.8'

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: shopping-cart-backend:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/shopping-cart
      - JWT_SECRET=${JWT_SECRET:-dev-secret}
    depends_on:
      - mongodb

  frontend:
    image: shopping-cart-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
